POST http://127.0.0.1:3001/api/user HTTP/1.1
Content-Type: application/json

{
  "name": "李北群",
  "password": "114514",
  "stuNum": "1145141919",
  "collage": "行政楼",
  "class": "114班"
}

###
POST http://127.0.0.1:3001/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "password": "114514",
  "stuNum": "1145141919"
}

###
GET http://127.0.0.1:3001/api/user/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWQwMTA1ZGY0OGM3OWJjMGY5YzAyZCIsImlhdCI6MTY1MDI2NDY0MDg3MH0.a6Oue1TdDWL40nd6by7zYdEUlHXbtG8YnBkYKazt2rQ

###
GET http://127.0.0.1:3001/api/auth/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWQwMTA1ZGY0OGM3OWJjMGY5YzAyZCIsImlhdCI6MTY1MDI2NDY0MDg3MH0.a6Oue1TdDWL40nd6by7zYdEUlHXbtG8YnBkYKazt2rQ

###
POST http://127.0.0.1:3001/api/book HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWQwMTA1ZGY0OGM3OWJjMGY5YzAyZCIsImlhdCI6MTY1MDI2NDY0MDg3MH0.a6Oue1TdDWL40nd6by7zYdEUlHXbtG8YnBkYKazt2rQ

{
  "title": "家庭、私有制和国家的起源",
  "desc": "123",
  "author": "123",
  "tags": [],
  "img": ""
}

###
GET http://127.0.0.1:3001/api/book HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyNWQwMTA1ZGY0OGM3OWJjMGY5YzAyZCIsImlhdCI6MTY1MDI2NDY0MDg3MH0.a6Oue1TdDWL40nd6by7zYdEUlHXbtG8YnBkYKazt2rQ